#!/bin/bash

server_ip="$1"

if ssh "$server_ip" "uname -s" | grep -q "Linux"; then
  echo "Server is Linux"
elif ssh "$server_ip" "netstat -a" | grep -q "LISTEN" | grep -q ":445"; then
  echo "Server is Windows (SMB port open)"
elif ssh -o ConnectTimeout=5 "$server_ip" "echo $SSH_SERVER" | grep -q "Linux"; then
  echo "Server is Linux (SSH banner)"
elif ssh -o ConnectTimeout=5 "$server_ip" "echo $SSH_SERVER" | grep -q "Microsoft"; then
  echo "Server is Windows (SSH banner)"
else
  echo "Unable to determine server OS"
fi
